docks: add instruction to replace perseus_integration
framesurge/perseus pull request #197
Opened 2022-09-30 06:53 UTC by Arrekin

I didn't want to edit your in-depth explanation from the foldable pane, and without that, it would be kind of duplication, so instead, I opted to add a comment to the main.rs example. That way, if someone just copies the code, he'll have information right there, without the need to dig through the page.

I saw other integrations, so I added them, but maybe you don't want them exposed - let me know if you want some tweaking on this.

2022-10-05 07:54 UTC, arctic-hen7 requested changes
Sorry for the late reply, I've been really busy lately! This looks great, just one minor wording thing I'd change, as I've noted.

2022-10-05 07:54 UTC, arctic-hen7 commented on examples/.base/src/main.rs
> +/// - perseus_warp (use this one if you follow basic tutorials)
```suggestion
/// - perseus_warp (recommended)
```

2022-10-06 05:51 UTC, Arrekin commented
Requested change applied.

2022-10-17 04:30 UTC, arctic-hen7 approved these changes
Sorry for the delay, I completely forgot to actually merge this lol!

2022-10-17 04:30 UTC, merged

2022-10-28 23:57 UTC, arctic-hen7 commented
@Arrekin just so you're aware, I've had to undo your code in fixing #212 by aliasing all instances of `perseus-integration` to `perseus-warp`, which should hopefully render this a non-issue in future!