Perseus rocket integration
framesurge/perseus pull request #266
Opened 2023-03-07 18:09 UTC by Miroito

This is a rocket integration for perseus.

I have mainly tried to translate the other integrations into the rocket structure.

Here are a few notes I think are worth pointing out:
- I made the decision to return a rocket base app instead of routes in the default function (usually called `perseus_routes`), I find it more convenient for this case but it is probably possible to return a list of routes as long as the developer that will write a custom server later remembers to manage the variable `opts`. This constraint can be worked around the same way I worked around the issue with the turbine containing generics.
- I'm not very confident that it will work with all perseus features right away, since I lack knowledge on the insides of perseus, I have done some smoke tests though with build paths and incremental generation. I have not tried to use translations.

I'm not explaining the details of the code so you can have a clean view as a reviewer. That being said, I will happily explain and discuss my decisions when prompted.

Lastly, I hope the current CI is able to test if this integration is fully compatible with perseus. I'm open to feedback there, maybe something I could write that would make sure this integration works now and for the future.

2023-03-09 01:56 UTC, arctic-hen7 commented
Thank you so much for this! You should be able to integrate it into the CI system quite simply, by adding this line to the bottom of the script in `bonnie.toml` with the key `test.subcommands.example-all-integrations.cmd` (line 197 I think):

```
"EXAMPLE_INTEGRATION=rocket bonnie dev example %category %example test"
```

That will add the rocket integration to all the tests, except those that are integration-locked, which will behave as you'd expect.

2023-03-09 12:02 UTC, Miroito commented
Thanks for the feedback.

I have run the tests, and everything passes for me with this latest commit.

The initial load handler route that matches everything now has a rank of 100 instead of 0 because FileServer rocket routes default to 10. And that's the only change done to actual behavior.

2023-03-11 20:25 UTC, Miroito commented
Rebased on main to fix the cargo_toml issue.

2023-03-12 00:41 UTC, arctic-hen7 commented
If everything is passing on your machine, that is fine. The i18n test is temperamental to say the least, and capsules sometimes fails as well. I usually just re-run them and wait for them to work. If it fails three times, I run locally. I will get around to automating the re-running of failing tests at some stage...\

I'm just releasing a new version to fix `cargo_toml` dependence (since that's breaking all new installations of the CLI), and then I'll merge this.

2023-03-12 18:10 UTC, Miroito commented
I just realized I forgot to figure out how to give the host parameter to Rocket.

Maybe there are more things I forgot about, please don't hesitate to look thoroughly and I'll make the changes.

2023-03-21 12:18 UTC, Miroito commented
Took the time to run the tests today with the latest commits and everything is successful locally.

2023-04-03 02:39 UTC, arctic-hen7 requested changes
Just a few minor suggestions and this should be good to merge! Thank you so much for all your hard work!

P.S. Sorry for taking so long to get to this properly, I've been very busy the last few weeks.

2023-04-03 02:39 UTC, arctic-hen7 commented on examples/core/custom_server_rocket/Cargo.toml
> +version = "0.4.0-beta.21"
```suggestion
version = "0.4.0-beta.22"
```

2023-04-03 02:39 UTC, arctic-hen7 commented on examples/core/custom_server_rocket/README.md
> +This is an example of setting up a custom server using rocket with Perseus, with one example api route.
```suggestion
This is an example of setting up a custom server using rocket with Perseus, with one example API route.
```

2023-04-03 02:39 UTC, arctic-hen7 commented on examples/core/custom_server_rocket/src/main.rs
> +    let mut config = rocket::Config::default();
Can you use the `host` here as well please, just so people know how to?

2023-04-03 02:39 UTC, arctic-hen7 commented on examples/core/custom_server_rocket/src/templates/index.rs
Could you copy the `index.rs` from `examples/core/basic/src/templates/index.rs` to keep the functionality in here to an absolute minimum?

2023-04-03 02:39 UTC, arctic-hen7 commented on packages/perseus-rocket/Cargo.toml
> +version = "0.4.0-beta.21"
```suggestion
version = "0.4.0-beta.22"
```

2023-04-03 02:39 UTC, arctic-hen7 commented on packages/perseus-rocket/src/lib.rs
> +// ----- Rocket Hanlder trait implementation -----
```suggestion
// ----- Rocket handler trait implementation -----
```

2023-04-03 02:39 UTC, arctic-hen7 commented on packages/perseus-rocket/src/lib.rs
> +/// This returns a rocket at the build stage that can be built upon further with
```suggestion
/// This returns a Rocket app at the build stage that can be built upon further with
```

2023-04-03 02:39 UTC, arctic-hen7 commented on packages/perseus-rocket/README.md
Could you make it clear in here that this integration is specially for Rocket v0.5, since that's still in beta? This warning can be removed once the Rocket devs release that version more stably.

2023-04-05 03:29 UTC, arctic-hen7 requested changes
Just a few very tiny things (one that I missed in the last pass).

Also thank you for your kind words, I try to make sure I really understand any code that's contributed to my projects, because I know that, at some stage, I'll probably have to wrangle with it! As for middleware, that's all very much theoretical right now, but I thank you very much for the offer!

2023-04-05 03:29 UTC, arctic-hen7 commented on packages/perseus-rocket/README.md
> +This is the official [Perseus](https://github.com/arctic-hen7/perseus) integration for making serving your apps on [Rocket](https://rocket.rs/) significantly easier!
```suggestion
This is the official [Perseus](https://github.com/framesurge/perseus) integration for making serving your apps on [Rocket](https://rocket.rs/) significantly easier!
```

2023-04-05 03:29 UTC, arctic-hen7 commented on packages/perseus-rocket/src/lib.rs
> +This is the API documentation for the `perseus-warp` package, which allows Perseus apps to run on Warp. Note that Perseus mostly uses [the book](https://framesurge.sh/perseus/en-US) for
```suggestion
This is the API documentation for the `perseus-rocket` package, which allows Perseus apps to run on Rocket. Note that Perseus mostly uses [the book](https://framesurge.sh/perseus/en-US) for
```

2023-04-05 03:30 UTC, arctic-hen7 commented
Also I wouldn't worry about the CI for now, I'll sort that out on my end once this is merged. Most things are clearly working, and the CI is, as I said earlier, temperamental.

2023-04-05 17:10 UTC, Miroito commented
There you go, I made many more than 2 passes and did not catch those issues, hopefully it's the last that remains from my careless copy pasting.

I believe some of those links (the perseus repo link mainly) are outdated in other packages, I have copied basically all comments from the axum or warp integration (I don't remember which) and they still mention your own repo (not framesurge). It's out of scope for this PR though so I did not make any changes there.

2023-04-06 04:25 UTC, arctic-hen7 commented
No problem! Yeah, I did a find-and-replace a long time ago to fix those which seemed to miss a few (dozen) files, which have slowly cropped up over time. There are redirects all in place so it's not a big deal, but I'll take a closer look and see where the leftovers are throughout the repo. With all that done, I think this is good to merge!

Once again, thank you so much for all your hard work on this, it really is greatly appreciated!

2023-04-06 04:26 UTC, merged