Engine Brotli compressed and optional http servers compression
framesurge/perseus pull request #300
Opened 2023-07-07 08:16 UTC by JT117

Relates to #199 

### Goal 1: Serve brotli pre compressed perseus engine files 

- Change perseus-cli to brotli compress the engine files after building them (maybe better to add it in the cmds vec ?)
- Add a flag in the perseus-cli to deactivate the brotli compress file generation: disable_engine_compression
- Change the servers configuration to serve the .br files first and if not found defaults to the uncompressed file.

#### Result :
On the basic example: 
| Mode            | File                | raw kB      |  brotli kB  |
| ------------- | -------------  | ---------- | ---------- |
| serve            | bundle.js        |  42.42       | 6.5           |
|                     | bundle.wasm  | 2980        | 554.71     |
| deploy          | bundle.js        |  32.43       | 5.23         |
|                     | bundle.wasm  | 315.98      | 109.62     |

The lighthouse score on mobile goes up from 97% to 100%
On my app it goes from 89% to 100% on mobile.

Remarks: Each server has it's own way to do thing, it goes from simple to I had to make a new Responder for Rocket

### Goal 2: Add the possibility for users to enable http compression on the servers

- Add on actix-web, axum, rocket and warp a new features: dflt-server-with-compression
- If the features is enabled, the server activate native compression

#### Result:
On the basic example: 

|     Server | File     | raw (kB) | compressed (kB) | Type   |
|----------|-------|----------|------------------| -------|
| rocket      | index    | 1.010           | 0.638  | brotli |
|                | about    | 0.927           | 0.328  | brotli |
| warp        | index    | 1.010           | 0.657  | gzip   |
|                 | about    | 0.927           | 0.611  | gzip   |
| actix-web | index    | 1.010           | 0.694  | gzip   |
|                 | about    | 0.927           | 0.647  | gzip   |
| axum       | index    | 1.010           | 0.657  | gzip   |
|                | about    | 0.927           | 0.610  | gzip   |

I would be happy to discuss the changes 😄 , and explain the choices that I made

2023-09-08 05:17 UTC, arctic-hen7 requested changes
Thank you so much for all this, it's really impressive! The benchmarks speak for themselves I think, and this is definitely something I want to get into Perseus sooner rather than later: my only big question is about the Rocket implementation, because it seems like a lot of code for something that's fairly simple in the other servers. Could you explain why all this is necessary? (I've tried to keep the server integrations as simple as possible, is there perhaps some way you could think of refactoring the core so we minimise the amount of code for the servers?)

As for having compression in the CLI have its own spinner, how long have you observed compression taking for the examples? Also, I would suggest having the `dflt-server-with-compression` flag activate a function with a unique name so the features aren't mutually exclusive (who knows, there may be some exotic configuration using both, but I don't see any reason to force the user into only having one). Also, I recommend changing `disable_engine_compression` to `disable_bundle_compression` to make what that flag does clearer by name in the CLI. I've left some more detailed minor suggestions (whitespace etc.) in my review.

Also, do you want to move the compression process in the CLI to the deployment system? That would avoid unnecessarily slowing down development builds (which generate multi-MB Wasm bundles, compression of which seems pointless and slow), and it would also make sure you compress the post-minification JS bundle.

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-actix-web/src/lib.rs
> +        Ok(file) => Ok( file.customize()
```suggestion
        Ok(file) => Ok(file.customize()
```

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-actix-web/src/lib.rs
> +                Ok(file) => Ok( file.customize()
```suggestion
                Ok(file) => Ok(file.customize()
```

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-actix-web/src/lib.rs
> +pub async fn dflt_server<M: MutableStore + 'static, T: TranslationsManager + 'static>(
```suggestion
pub async fn dflt_server_with_compression<M: MutableStore + 'static, T: TranslationsManager + 'static>(
```

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-axum/Cargo.toml
> +dflt-server-with-compression = ["tower-http/compression-gzip"]
```suggestion
dflt-server-with-compression = [ "tower-http/compression-gzip" ]
```

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-axum/src/lib.rs
> +pub async fn dflt_server<M: MutableStore + 'static, T: TranslationsManager + 'static>(
```suggestion
pub async fn dflt_server_with_compression<M: MutableStore + 'static, T: TranslationsManager + 'static>(
```

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-cli/src/build.rs
> +            // If the compression is enable (enabled by default), we brotli compress each file in the `dist/pkg` directory
```suggestion
            // If compression is enabled (which it is by default), we compress each file with Brotli in `dist/pkg`
```

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-cli/src/build.rs
> +            // Make this a step in the build process with a dedicated spinner ? How to make it work in the cmds arrays ?
```suggestion
```

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-cli/src/build.rs
There are only ever two files in `dist/pkg/` that matter: the Wasm bundle and the JS bundle. The other two are types files that are presently unused, and compressing them seems unnecessary. I would suggest simplifying this code by avoiding walking the directory and instead just directly compressing those two files.

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-cli/src/parse.rs
> +    /// Deactivate the brotli compression of the engine files
```suggestion
    /// Disable Brotli compression of JS and Wasm bundles (may degrade performance)
```

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-rocket/Cargo.toml
> +rocket_async_compression_lib = { version = "0.5.0", optional = true, package = "rocket_async_compression" }
Why not use the regular package name?

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-rocket/Cargo.toml
> +dflt-server-with-compression = ["rocket_async_compression_lib"]
```suggestion
dflt-server-with-compression = [ "rocket_async_compression_lib" ]
```

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-rocket/src/lib.rs
> +pub async fn dflt_server<M: MutableStore + 'static, T: TranslationsManager + 'static>(
```suggestion
pub async fn dflt_server_with_compression<M: MutableStore + 'static, T: TranslationsManager + 'static>(
```

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-rocket/src/pre_compressed_named_file.rs
As per the whole-review comment, is all this really necessary?

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-warp/Cargo.toml
> +dflt-server-with-compression = ["warp/compression"]
```suggestion
dflt-server-with-compression = [ "warp/compression" ]
```

2023-09-08 05:17 UTC, arctic-hen7 commented on packages/perseus-warp/src/lib.rs
> +pub async fn dflt_server<M: MutableStore + 'static, T: TranslationsManager + 'static>(
```suggestion
pub async fn dflt_server_with_compression<M: MutableStore + 'static, T: TranslationsManager + 'static>(
```

2023-10-06 13:02 UTC, JT117 commented
Thanks for the feedback :)
I'm on it, I will look again at rocket to see if I missed something, compress only the js and wasm bundle, change the flag name to
disable_bundle_compression and accept all the corrections you made

2023-10-06 15:21 UTC, JT117 commented on packages/perseus-rocket/src/pre_compressed_named_file.rs
Oh my, I just re looked over, I have a much simpler way, update incoming

2023-10-19 00:49 UTC, arctic-hen7 approved these changes
This is looking really fantastic, thank you so much for all your hard work, it's greatly appreciated!

2023-10-19 00:51 UTC, arctic-hen7 commented
I've just resolved a tiny conflict (Git being very silly), and, once tests are passing, this should be good to merge! Thanks again!

2023-12-12 22:03 UTC, arctic-hen7 approved these changes
Fabulous, thanks so much for all this!

2023-12-12 22:05 UTC, merged